export interface StudioServiceWorkerAsset {
  url: string;
  revision: string;
  size: number;
}

interface StudioServiceWorkerOptions {
  appName: string;
  appVersion: string;
  cacheVersion: string;
  baseUrl: string;
  navigationFallbackUrl: string;
  assets: StudioServiceWorkerAsset[];
}

const toJson = (value: unknown) => JSON.stringify(value, null, 2);

export const normalizePwaBasePath = (base: string): string => {
  if (!base || base === './') return '/';

  let next = base;
  if (/^https?:\/\//i.test(next)) {
    next = new URL(next).pathname;
  }

  if (!next.startsWith('/')) {
    next = `/${next}`;
  }
  if (!next.endsWith('/')) {
    next = `${next}/`;
  }
  return next;
};

export const createStudioServiceWorkerSource = ({
  appName,
  appVersion,
  cacheVersion,
  baseUrl,
  navigationFallbackUrl,
  assets,
}: StudioServiceWorkerOptions): string => {
  const normalizedBaseUrl = normalizePwaBasePath(baseUrl);

  return `/* generated by apps/studio/vite.config.ts */
const APP_NAME = ${toJson(appName)};
const APP_VERSION = ${toJson(appVersion)};
const CACHE_VERSION = ${toJson(cacheVersion)};
const BASE_URL = ${toJson(normalizedBaseUrl)};
const NAVIGATION_FALLBACK_URL = ${toJson(navigationFallbackUrl)};
const PRECACHE_ASSETS = ${toJson([
    { url: normalizedBaseUrl, revision: cacheVersion, size: 0 },
    ...assets,
  ])};

const CACHE_PREFIX = 'blackboard-studio';
const PRECACHE_CACHE = \`\${CACHE_PREFIX}-precache-\${CACHE_VERSION}\`;
const RUNTIME_CACHE = \`\${CACHE_PREFIX}-runtime-\${CACHE_VERSION}\`;
const BASE_PATH = new URL(BASE_URL, self.location.origin).pathname;
const PRECACHE_URLS = new Set(
  PRECACHE_ASSETS.map((asset) => new URL(asset.url, self.location.origin).href),
);

const getVersionPayload = () => ({
  type: 'BLACKBOARD_STUDIO_SW_VERSION',
  appName: APP_NAME,
  appVersion: APP_VERSION,
  cacheVersion: CACHE_VERSION,
  assetCount: PRECACHE_ASSETS.length,
});

const getCacheKey = (requestOrUrl) => {
  const url = new URL(
    typeof requestOrUrl === 'string' ? requestOrUrl : requestOrUrl.url,
    self.location.origin,
  );
  url.hash = '';
  url.search = '';
  return url.href;
};

const isScopedGetRequest = (request) => {
  if (request.method !== 'GET') return false;
  const url = new URL(request.url);
  return url.origin === self.location.origin && url.pathname.startsWith(BASE_PATH);
};

const writePrecache = async () => {
  const cache = await caches.open(PRECACHE_CACHE);

  await Promise.all(
    PRECACHE_ASSETS.map(async (asset) => {
      const response = await fetch(new Request(asset.url, { cache: 'reload' }));
      if (!response.ok) {
        throw new Error(\`Could not precache \${asset.url}: \${response.status}\`);
      }
      await cache.put(getCacheKey(asset.url), response);
    }),
  );
};

const deleteOldCaches = async () => {
  const cacheNames = await caches.keys();
  await Promise.all(
    cacheNames
      .filter(
        (cacheName) =>
          cacheName.startsWith(\`\${CACHE_PREFIX}-\`) &&
          cacheName !== PRECACHE_CACHE &&
          cacheName !== RUNTIME_CACHE,
      )
      .map((cacheName) => caches.delete(cacheName)),
  );
};

const getPrecachedResponse = async (request) => {
  const cache = await caches.open(PRECACHE_CACHE);
  return (
    (await cache.match(getCacheKey(request))) ??
    (await cache.match(getCacheKey(NAVIGATION_FALLBACK_URL))) ??
    (await cache.match(getCacheKey(BASE_URL)))
  );
};

const handleNavigation = async (request) => {
  const cache = await caches.open(PRECACHE_CACHE);

  try {
    const response = await fetch(request);
    if (response.ok) {
      await cache.put(getCacheKey(NAVIGATION_FALLBACK_URL), response.clone());
      return response;
    }
  } catch {
    // Fall through to the cached app shell.
  }

  const fallback = await getPrecachedResponse(request);
  return fallback ?? Response.error();
};

const handlePrecachedAsset = async (request) => {
  const cached = await getPrecachedResponse(request);
  return cached ?? fetch(request);
};

const isRuntimeCacheCandidate = (request) => {
  const url = new URL(request.url);
  if (!url.pathname.startsWith(BASE_PATH)) return false;

  const destination = request.destination;
  if (['font', 'image', 'manifest', 'script', 'style', 'worker'].includes(destination)) {
    return true;
  }

  return /\\.(css|html|js|json|mjs|png|svg|wasm|webmanifest)$/i.test(url.pathname);
};

const handleRuntimeAsset = async (request) => {
  const cache = await caches.open(RUNTIME_CACHE);
  const cacheKey = getCacheKey(request);
  const cached = await cache.match(cacheKey);

  const networkRequest = fetch(request)
    .then(async (response) => {
      if (response.ok) {
        await cache.put(cacheKey, response.clone());
      }
      return response;
    })
    .catch(() => undefined);

  return cached ?? (await networkRequest) ?? Response.error();
};

const notifyClients = async (message) => {
  const clients = await self.clients.matchAll({ type: 'window' });
  clients.forEach((client) => client.postMessage(message));
};

self.addEventListener('install', (event) => {
  event.waitUntil(writePrecache());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      await deleteOldCaches();
      await self.clients.claim();
      await notifyClients({
        type: 'BLACKBOARD_STUDIO_SW_ACTIVATED',
        ...getVersionPayload(),
      });
    })(),
  );
});

self.addEventListener('message', (event) => {
  const type = event.data?.type;
  if (type === 'BLACKBOARD_STUDIO_SKIP_WAITING') {
    self.skipWaiting();
    return;
  }

  if (type === 'BLACKBOARD_STUDIO_GET_VERSION') {
    event.ports?.[0]?.postMessage(getVersionPayload());
  }
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (!isScopedGetRequest(request)) return;

  if (request.mode === 'navigate') {
    event.respondWith(handleNavigation(request));
    return;
  }

  if (PRECACHE_URLS.has(getCacheKey(request))) {
    event.respondWith(handlePrecachedAsset(request));
    return;
  }

  if (isRuntimeCacheCandidate(request)) {
    event.respondWith(handleRuntimeAsset(request));
  }
});
`;
};
