export interface StudioServiceWorkerAsset {
  url: string;
  revision: string;
  size: number;
  group?: string;
  label?: string;
  description?: string;
  removable?: boolean;
}

export interface StudioServiceWorkerAssetGroup {
  id: string;
  label: string;
  description: string;
  removable: boolean;
  assetCount: number;
  size: number;
}

interface StudioServiceWorkerOptions {
  appName: string;
  appVersion: string;
  cacheVersion: string;
  baseUrl: string;
  navigationFallbackUrl: string;
  precacheAssets: StudioServiceWorkerAsset[];
  runtimeAssets?: StudioServiceWorkerAsset[];
}

const toJson = (value: unknown) => JSON.stringify(value, null, 2);

export const normalizePwaBasePath = (base: string): string => {
  if (!base || base === './') return '/';

  let next = base;
  if (/^https?:\/\//i.test(next)) {
    next = new URL(next).pathname;
  }

  if (!next.startsWith('/')) {
    next = `/${next}`;
  }
  if (!next.endsWith('/')) {
    next = `${next}/`;
  }
  return next;
};

const summarizeAssetGroups = (
  runtimeAssets: StudioServiceWorkerAsset[],
): StudioServiceWorkerAssetGroup[] => {
  const groups = new Map<string, StudioServiceWorkerAssetGroup>();

  runtimeAssets.forEach((asset) => {
    const id = asset.group ?? 'feature-assets';
    const existing = groups.get(id);
    if (existing) {
      existing.assetCount += 1;
      existing.size += asset.size;
      existing.removable = existing.removable && (asset.removable ?? true);
      return;
    }

    groups.set(id, {
      id,
      label: asset.label ?? 'Feature assets',
      description: asset.description ?? 'Optional files cached when the related feature is used.',
      removable: asset.removable ?? true,
      assetCount: 1,
      size: asset.size,
    });
  });

  return Array.from(groups.values()).sort((a, b) => b.size - a.size);
};

export const createStudioServiceWorkerSource = ({
  appName,
  appVersion,
  cacheVersion,
  baseUrl,
  navigationFallbackUrl,
  precacheAssets,
  runtimeAssets = [],
}: StudioServiceWorkerOptions): string => {
  const normalizedBaseUrl = normalizePwaBasePath(baseUrl);
  const precacheManifest = [
    { url: normalizedBaseUrl, revision: cacheVersion, size: 0 },
    ...precacheAssets,
  ];
  const runtimeAssetGroups = summarizeAssetGroups(runtimeAssets);

  return `/* generated by apps/studio/vite.config.ts */
const APP_NAME = ${toJson(appName)};
const APP_VERSION = ${toJson(appVersion)};
const CACHE_VERSION = ${toJson(cacheVersion)};
const BASE_URL = ${toJson(normalizedBaseUrl)};
const NAVIGATION_FALLBACK_URL = ${toJson(navigationFallbackUrl)};
const PRECACHE_ASSETS = ${toJson(precacheManifest)};
const RUNTIME_ASSETS = ${toJson(runtimeAssets)};
const RUNTIME_ASSET_GROUPS = ${toJson(runtimeAssetGroups)};

const CACHE_PREFIX = 'blackboard-studio';
const PRECACHE_CACHE = \`\${CACHE_PREFIX}-precache-\${CACHE_VERSION}\`;
const RUNTIME_CACHE = \`\${CACHE_PREFIX}-runtime-\${CACHE_VERSION}\`;
const BASE_PATH = new URL(BASE_URL, self.location.origin).pathname;
const PRECACHE_URLS = new Set(
  PRECACHE_ASSETS.map((asset) => new URL(asset.url, self.location.origin).href),
);
const RUNTIME_URLS = new Set(
  RUNTIME_ASSETS.map((asset) => new URL(asset.url, self.location.origin).href),
);
const sumAssetBytes = (assets) => assets.reduce((total, asset) => total + (asset.size || 0), 0);
const getAssetGroupId = (asset) => asset.group || 'feature-assets';
const getRuntimeAssetGroup = (groupId) =>
  RUNTIME_ASSET_GROUPS.find((group) => group.id === groupId);
const getRuntimeAssetsForGroup = (groupId) =>
  RUNTIME_ASSETS.filter((asset) => getAssetGroupId(asset) === groupId);
const getRemovableRuntimeAssets = () => {
  const removableGroupIds = new Set(
    RUNTIME_ASSET_GROUPS.filter((group) => group.removable !== false).map((group) => group.id),
  );
  return RUNTIME_ASSETS.filter((asset) => removableGroupIds.has(getAssetGroupId(asset)));
};

const getVersionPayload = () => ({
  type: 'BLACKBOARD_STUDIO_SW_VERSION',
  appName: APP_NAME,
  appVersion: APP_VERSION,
  cacheVersion: CACHE_VERSION,
  assetCount: PRECACHE_ASSETS.length,
  precacheAssetCount: PRECACHE_ASSETS.length,
  runtimeAssetCount: RUNTIME_ASSETS.length,
  precacheBytes: sumAssetBytes(PRECACHE_ASSETS),
  runtimeBytes: sumAssetBytes(RUNTIME_ASSETS),
  runtimeAssetGroups: RUNTIME_ASSET_GROUPS,
});

const summarizeCachedAssets = async (cache, assets) => {
  let cachedAssetCount = 0;
  let cachedBytes = 0;

  for (const asset of assets) {
    if (await cache.match(getCacheKey(asset.url))) {
      cachedAssetCount += 1;
      cachedBytes += asset.size || 0;
    }
  }

  return {
    assetCount: assets.length,
    size: sumAssetBytes(assets),
    cachedAssetCount,
    cachedBytes,
  };
};

const getRuntimeCacheGroups = async () => {
  const cache = await caches.open(RUNTIME_CACHE);
  const groups = new Map(
    RUNTIME_ASSET_GROUPS.map((group) => [
      group.id,
      {
        ...group,
        cachedAssetCount: 0,
        cachedBytes: 0,
      },
    ]),
  );

  for (const asset of RUNTIME_ASSETS) {
    const groupId = getAssetGroupId(asset);
    const group = groups.get(groupId);
    if (!group) continue;

    if (await cache.match(getCacheKey(asset.url))) {
      group.cachedAssetCount += 1;
      group.cachedBytes += asset.size || 0;
    }
  }

  return Array.from(groups.values()).sort((a, b) => b.size - a.size);
};

const getCacheStatusPayload = async () => {
  const precache = await caches.open(PRECACHE_CACHE);
  const precacheStatus = await summarizeCachedAssets(precache, PRECACHE_ASSETS);
  const runtimeAssetGroups = await getRuntimeCacheGroups();
  const runtimeCachedAssetCount = runtimeAssetGroups.reduce(
    (total, group) => total + group.cachedAssetCount,
    0,
  );
  const runtimeCachedBytes = runtimeAssetGroups.reduce(
    (total, group) => total + group.cachedBytes,
    0,
  );

  return {
    ...getVersionPayload(),
    type: 'BLACKBOARD_STUDIO_SW_CACHE_STATUS',
    precacheCachedAssetCount: precacheStatus.cachedAssetCount,
    precacheCachedBytes: precacheStatus.cachedBytes,
    runtimeCachedAssetCount,
    runtimeCachedBytes,
    totalCachedBytes: precacheStatus.cachedBytes + runtimeCachedBytes,
    runtimeAssetGroups,
  };
};

const cacheRuntimeAssets = async (groupId) => {
  const targetAssets = groupId
    ? getRuntimeAssetsForGroup(groupId)
    : RUNTIME_ASSETS;

  if (groupId && targetAssets.length === 0) {
    throw new Error('Unknown on-demand asset group.');
  }

  const cache = await caches.open(RUNTIME_CACHE);

  for (const asset of targetAssets) {
    const cacheKey = getCacheKey(asset.url);
    if (await cache.match(cacheKey)) continue;

    const response = await fetch(new Request(asset.url, { cache: 'reload' }));
    if (!response.ok) {
      throw new Error(\`Could not download \${asset.label || asset.url}: \${response.status}\`);
    }
    await cache.put(cacheKey, response);
  }

  return getCacheStatusPayload();
};

const deleteRuntimeAssets = async (groupId) => {
  const group = groupId ? getRuntimeAssetGroup(groupId) : null;
  if (groupId && !group) {
    throw new Error('Unknown on-demand asset group.');
  }
  if (group?.removable === false) {
    throw new Error('This on-demand asset group cannot be removed.');
  }

  const targetAssets = groupId ? getRuntimeAssetsForGroup(groupId) : getRemovableRuntimeAssets();
  const cache = await caches.open(RUNTIME_CACHE);
  await Promise.all(targetAssets.map((asset) => cache.delete(getCacheKey(asset.url))));

  return getCacheStatusPayload();
};

const getCacheKey = (requestOrUrl) => {
  const url = new URL(
    typeof requestOrUrl === 'string' ? requestOrUrl : requestOrUrl.url,
    self.location.origin,
  );
  url.hash = '';
  url.search = '';
  return url.href;
};

const isScopedGetRequest = (request) => {
  if (request.method !== 'GET') return false;
  const url = new URL(request.url);
  return url.origin === self.location.origin && url.pathname.startsWith(BASE_PATH);
};

const writePrecache = async () => {
  const cache = await caches.open(PRECACHE_CACHE);

  await Promise.all(
    PRECACHE_ASSETS.map(async (asset) => {
      const response = await fetch(new Request(asset.url, { cache: 'reload' }));
      if (!response.ok) {
        throw new Error(\`Could not precache \${asset.url}: \${response.status}\`);
      }
      await cache.put(getCacheKey(asset.url), response);
    }),
  );
};

const deleteOldCaches = async () => {
  const cacheNames = await caches.keys();
  await Promise.all(
    cacheNames
      .filter(
        (cacheName) =>
          cacheName.startsWith(\`\${CACHE_PREFIX}-\`) &&
          cacheName !== PRECACHE_CACHE &&
          cacheName !== RUNTIME_CACHE,
      )
      .map((cacheName) => caches.delete(cacheName)),
  );
};

const getPrecachedResponse = async (request) => {
  const cache = await caches.open(PRECACHE_CACHE);
  return (
    (await cache.match(getCacheKey(request))) ??
    (await cache.match(getCacheKey(NAVIGATION_FALLBACK_URL))) ??
    (await cache.match(getCacheKey(BASE_URL)))
  );
};

const handleNavigation = async (request) => {
  const cache = await caches.open(PRECACHE_CACHE);

  try {
    const response = await fetch(request);
    if (response.ok) {
      await cache.put(getCacheKey(NAVIGATION_FALLBACK_URL), response.clone());
      return response;
    }
  } catch {
    // Fall through to the cached app shell.
  }

  const fallback = await getPrecachedResponse(request);
  return fallback ?? Response.error();
};

const handlePrecachedAsset = async (request) => {
  const cached = await getPrecachedResponse(request);
  return cached ?? fetch(request);
};

const isRuntimeCacheCandidate = (request) => {
  const url = new URL(request.url);
  if (!url.pathname.startsWith(BASE_PATH)) return false;

  const destination = request.destination;
  if (['font', 'image', 'manifest', 'script', 'style', 'worker'].includes(destination)) {
    return true;
  }

  return /\\.(css|html|js|json|mjs|png|svg|wasm|webmanifest)$/i.test(url.pathname);
};

const notifyClients = async (message) => {
  const clients = await self.clients.matchAll({ type: 'window' });
  clients.forEach((client) => client.postMessage(message));
};

const notifyCacheStatus = async () => {
  await notifyClients(await getCacheStatusPayload());
};

const handleRuntimeAsset = async (request) => {
  const cache = await caches.open(RUNTIME_CACHE);
  const cacheKey = getCacheKey(request);
  const cached = await cache.match(cacheKey);

  const networkRequest = fetch(request)
    .then(async (response) => {
      if (response.ok) {
        await cache.put(cacheKey, response.clone());
        void notifyCacheStatus();
      }
      return response;
    })
    .catch(() => undefined);

  return cached ?? (await networkRequest) ?? Response.error();
};

self.addEventListener('install', (event) => {
  event.waitUntil(writePrecache());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      await deleteOldCaches();
      await self.clients.claim();
      await notifyClients({
        type: 'BLACKBOARD_STUDIO_SW_ACTIVATED',
        ...getVersionPayload(),
      });
    })(),
  );
});

self.addEventListener('message', (event) => {
  const type = event.data?.type;
  if (type === 'BLACKBOARD_STUDIO_SKIP_WAITING') {
    self.skipWaiting();
    return;
  }

  if (type === 'BLACKBOARD_STUDIO_GET_VERSION') {
    event.ports?.[0]?.postMessage(getVersionPayload());
    return;
  }

  if (type === 'BLACKBOARD_STUDIO_GET_CACHE_STATUS') {
    const port = event.ports?.[0];
    if (!port) return;
    event.waitUntil(
      getCacheStatusPayload()
        .then((status) => port.postMessage(status))
        .catch((error) =>
          port.postMessage({
            type: 'BLACKBOARD_STUDIO_SW_CACHE_STATUS',
            error: error instanceof Error ? error.message : String(error),
          }),
        ),
    );
    return;
  }

  if (type === 'BLACKBOARD_STUDIO_CACHE_RUNTIME_ASSETS') {
    const port = event.ports?.[0];
    if (!port) return;
    event.waitUntil(
      cacheRuntimeAssets(event.data?.groupId)
        .then((cacheStatus) =>
          port.postMessage({
            type: 'BLACKBOARD_STUDIO_SW_CACHE_RESULT',
            ok: true,
            operation: 'install',
            groupId: event.data?.groupId ?? null,
            cacheStatus,
          }),
        )
        .catch((error) =>
          port.postMessage({
            type: 'BLACKBOARD_STUDIO_SW_CACHE_RESULT',
            ok: false,
            operation: 'install',
            groupId: event.data?.groupId ?? null,
            error: error instanceof Error ? error.message : String(error),
          }),
        ),
    );
    return;
  }

  if (type === 'BLACKBOARD_STUDIO_DELETE_RUNTIME_ASSETS') {
    const port = event.ports?.[0];
    if (!port) return;
    event.waitUntil(
      deleteRuntimeAssets(event.data?.groupId)
        .then((cacheStatus) =>
          port.postMessage({
            type: 'BLACKBOARD_STUDIO_SW_CACHE_RESULT',
            ok: true,
            operation: 'remove',
            groupId: event.data?.groupId ?? null,
            cacheStatus,
          }),
        )
        .catch((error) =>
          port.postMessage({
            type: 'BLACKBOARD_STUDIO_SW_CACHE_RESULT',
            ok: false,
            operation: 'remove',
            groupId: event.data?.groupId ?? null,
            error: error instanceof Error ? error.message : String(error),
          }),
        ),
    );
  }
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (!isScopedGetRequest(request)) return;

  if (request.mode === 'navigate') {
    event.respondWith(handleNavigation(request));
    return;
  }

  if (PRECACHE_URLS.has(getCacheKey(request))) {
    event.respondWith(handlePrecachedAsset(request));
    return;
  }

  if (RUNTIME_URLS.has(getCacheKey(request)) || isRuntimeCacheCandidate(request)) {
    event.respondWith(handleRuntimeAsset(request));
  }
});
`;
};
