import {
  CacheStatus,
  EditorTab,
  Flow,
  FlowId,
  HistoryEntry,
  NodePositions,
  RenderSettings,
  RotoPath,
  RotoRefinement,
  SelectedKeyframeRef,
  TransformData,
  StabilizationConfig,
  ViewerSettings,
  QueuedAiGenerationTask,
  ViewerSlotAssignments,
  ViewerSlot,
} from '@blackboard/types';

export const getInitialHistoryEntry = (): HistoryEntry => ({
  id: `init_${Date.now()}`,
  label: 'Initial State',
  state: {
    flows: {},
    rootFlowId: null,
    activeFlowId: null,
    selectedNodeId: null,
    zoom: 1,
    pan: { x: 0, y: 0 },
    fps: 30,
  },
});

export const getInitialState = () => ({
  projectId: null as string | null,
  flows: {} as Record<FlowId, Flow>,
  rootFlowId: null as string | null,
  activeFlowId: null as string | null,
  selectedNodeId: null as string | null,
  selectedRotoPathIds: [] as string[],
  selectedRotoPointRefs: [] as import('@blackboard/types').RotoPointRef[],
  selectedPaintStrokeIds: [] as string[],
  selectedKeyframes: [] as SelectedKeyframeRef[],
  activeTab: EditorTab.Tools,
  zoom: 1,
  pan: { x: 0, y: 0 },
  targetZoom: 1,
  targetPan: { x: 0, y: 0 },
  history: [getInitialHistoryEntry()] as HistoryEntry[],
  historyIndex: 0,
  thumbnail: null as string | null,
  aiChats: [] as import('@blackboard/types').AiChatThread[],
  activeAiChatId: null as string | null,
  aiEditingNodeId: null as string | null,
  aiGenerationQueue: [] as QueuedAiGenerationTask[],
  isAiCurrentlyGenerating: false,
  isPlaying: false,
  currentFrame: 0,
  activeViewportTool: null as string | null,
  isDrawing: false,
  drawingRotoPath: null as RotoPath | null,
  drawingSubHistory: [] as RotoPath[],
  drawingSubHistoryIndex: -1,
  rotoRefinement: null as RotoRefinement | null,
  isStabilized: false,
  stabilizationReference: null as TransformData | null,
  stabilizationReferenceFrame: null as number | null,
  stabilizationConfig: {
    translation: true,
    rotation: true,
    scale: true,
    affine: true,
    perspective: true,
    scope: 'full',
  } as StabilizationConfig,
  viewerNodeId: null as string | null,
  viewerSlots: {} as ViewerSlotAssignments,
  activeViewerSlot: null as ViewerSlot | null,
  viewerSettings: {
    channels: 'RGB' as const,
    alphaOverlay: false,
    alphaMode: 'STRAIGHT' as const,
    showOverlays: true,
    ocioView: 'sRGB',
    gain: 1,
    gamma: 1,
    saturation: 1,
    lastCustomGain: 1,
    lastCustomGamma: 1,
    lastCustomSaturation: 1,
  } as ViewerSettings,
  renderSettings: {
    filename: 'export',
    format: 'image/jpeg' as const,
    quality: 90,
    outputColorSpace: 'srgb' as const,
    includeAlpha: false,
  } as RenderSettings,
  cacheStatus: {
    memoryUsed: 0,
    memoryLimit: 512 * 1024 * 1024,
    cachedFrames: [],
    cachingFrames: [],
  } as CacheStatus,
  activeTrackingPoints: null as { x: number; y: number }[] | null,
  fps: 30,
  nodePositionsByFlow: {} as Record<FlowId, NodePositions>,
});
