import {
  AiAgentRun,
  AiChatThread,
  CacheStatus,
  EditorTab,
  Flow,
  FlowId,
  HistoryEntry,
  NodePositions,
  NodeType,
  RenderSettings,
  RotoPath,
  RotoRefinement,
  RotoPointRef,
  SelectedKeyframeRef,
  TransformData,
  StabilizationConfig,
  ViewerSettings,
  ViewerSlotAssignments,
  ViewerSlot,
} from '@blackboard/types';
import { AnyNode } from '@blackboard/types';
import {
  loadPersistedBackgroundJobs,
  type BackgroundJob,
} from '@/state/editor/services/backgroundJobs';
import { MAIN_PROJECT_BRANCH_ID, type ProjectBranchRecord } from '@/state/projectBranches';

export const getInitialHistoryEntry = (): HistoryEntry => ({
  id: `init_${Date.now()}`,
  label: 'Initial State',
  state: {
    flows: {},
    rootFlowId: null,
    activeFlowId: null,
    selectedNodeId: null,
    selectedNodeIds: [],
    zoom: 1,
    pan: { x: 0, y: 0 },
    fps: 30,
  },
});

export const getInitialState = () => ({
  projectId: null as string | null,
  flows: {} as Record<FlowId, Flow>,
  rootFlowId: null as string | null,
  activeFlowId: null as string | null,
  selectedNodeId: null as string | null,
  selectedNodeIds: [] as string[],
  hierarchySelections: {} as Record<string, { layerIds: string[]; itemIds: string[] }>,
  selectedRotoPointRefs: [] as RotoPointRef[],
  selectedKeyframes: [] as SelectedKeyframeRef[],
  activeTab: EditorTab.Tools,
  zoom: 1,
  pan: { x: 0, y: 0 },
  targetZoom: 1,
  targetPan: { x: 0, y: 0 },
  history: [getInitialHistoryEntry()] as HistoryEntry[],
  historyIndex: 0,
  thumbnail: null as string | null,
  aiChats: [] as AiChatThread[],
  aiAgentRuns: [] as AiAgentRun[],
  activeAiAgentRunId: null as string | null,
  activeAiChatId: null as string | null,
  isPlaying: false,
  currentFrame: 0,
  activeViewportTool: null as string | null,
  isDrawing: false,
  drawingRotoPath: null as RotoPath | null,
  drawingSubHistory: [] as RotoPath[],
  drawingSubHistoryIndex: -1,
  rotoRefinement: null as RotoRefinement | null,
  isStabilized: false,
  stabilizationReference: null as TransformData | null,
  stabilizationReferenceFrame: null as number | null,
  stabilizationConfig: {
    translation: true,
    rotation: true,
    scale: true,
    affine: true,
    perspective: true,
    scope: 'full',
  } as StabilizationConfig,
  viewerNodeId: null as string | null,
  viewerSlots: {} as ViewerSlotAssignments,
  activeViewerSlot: null as ViewerSlot | null,
  viewerSettings: {
    channels: 'RGB' as const,
    alphaOverlay: false,
    alphaMode: 'STRAIGHT' as const,
    showOverlays: true,
    ocioDisplay: 'sRGB - Display',
    gain: 1,
    gamma: 1,
    saturation: 1,
    lastCustomGain: 1,
    lastCustomGamma: 1,
    lastCustomSaturation: 1,
  } as ViewerSettings,
  renderSettings: {
    exportMode: 'single' as const,
    filename: 'export',
    format: 'image/jpeg' as const,
    quality: 90,
    outputColorSpace: 'srgb' as const,
    includeAlpha: false,
    sequenceStartFrame: 0,
    sequencePadding: 4,
  } as RenderSettings,
  cacheStatus: {
    memoryUsed: 0,
    memoryLimit: 512 * 1024 * 1024,
    cachedFrames: [],
    cachingFrames: [],
  } as CacheStatus,
  activeTrackingPoints: null as { x: number; y: number }[] | null,
  fps: 30,
  nodePositionsByFlow: {} as Record<FlowId, NodePositions>,
  thumbnailAssetId: undefined as string | undefined,
  activeProjectBranchId: MAIN_PROJECT_BRANCH_ID,
  projectBranches: [] as ProjectBranchRecord[],
  isFrameScrubbing: false,
  playbackDirection: 1 as 1 | -1,
  isSubPanelVisible: true,
  aiApplyNotice: null as null | {
    id: string;
    nodeId: string;
    field: 'shader' | 'prompt' | 'grade' | 'comfy-output';
    fieldId?: string;
    label: string;
    createdAt: number;
  },
  nodes: [] as AnyNode[],
  backgroundJobs: loadPersistedBackgroundJobs() as BackgroundJob[],
  galleryUpdatedAt: 0 as number,
  pendingNodePosition: null as { x: number; y: number } | null,
  previewNodeType: null as NodeType | null,
});
