// @blackboard/project-store — Shared project persistence, asset storage, and gallery

// Asset storage (IndexedDB)
export {
  saveAsset,
  saveAssetToMount,
  getAsset,
  getAssetSize,
  getAssetReferenceExportRecord,
  deleteAssets,
  saveDirectoryAssetReferences,
  requestReferencePermissions,
  saveProjectStateToDB,
  loadProjectStateFromDB,
  deleteProjectStateFromDB,
  listProjectStateIdsFromDB,
  type AssetReferenceExportRecord,
  type SaveAssetOptions,
} from './assetStorage';

// Multi-mount storage and workspace/plugin file access
export {
  BROWSER_STORAGE_MOUNT_ID,
  STORAGE_MOUNT_RESOURCES,
  StorageMountPaths,
  normalizeStorageMountPath,
  joinStorageMountPath,
  getDefaultStorageMountId,
  setDefaultStorageMountId,
  subscribeToStorageMounts,
  createObjectStorageAdapter,
  registerStorageMount,
  mountDirectory,
  requestStorageMountPermission,
  unmountStorage,
  listStorageMounts,
  getStorageMount,
  readStorageFile,
  writeStorageFile,
  deleteStorageFile,
  listStorageFiles,
  deleteStorageTree,
  readWorkspaceFile,
  writeWorkspaceFile,
  deleteWorkspaceFile,
  listWorkspaceFiles,
  readPluginFile,
  writePluginFile,
  deletePluginFile,
  listPluginFiles,
  createMountedAssetId,
  parseMountedAssetId,
  createStorageMountAssetPath,
  type StorageMountResource,
  type StorageMountKind,
  type StorageMountDescriptor,
  type StorageMountInfo,
  type StorageMountFile,
  type StorageMountAdapter,
  type ObjectStorageClient,
  type StorageFileScopeOptions,
} from './storageMounts';

// Project persistence (localStorage + IndexedDB)
export {
  SCHEMA_VERSION,
  getProjectIndex,
  saveProjectIndex,
  saveProject,
  loadProjectState,
  deleteProject,
  getProjectStorageBinding,
  bindProjectToStorageMount,
  unbindProjectFromStorageMount,
  connectProjectRemote,
  cloneProjectToBrowser,
  pushProjectToRemote,
  pullProjectFromRemote,
  getProjectSyncStatus,
  getDefaultProjectStorageWorkflow,
  setDefaultProjectStorageWorkflow,
  subscribeToProjectStorage,
  registerProjectStorageMetadataProvider,
  refreshMountedProjectIndex,
  type ProjectStorageBinding,
  type ProjectSyncState,
  type ProjectSyncStatus,
  type ProjectStorageMetadataProvider,
} from './persist';

// App-level gallery store
export {
  loadGalleryEntries,
  addGalleryEntries,
  updateGalleryEntry,
  softDeleteGalleryEntries,
  restoreGalleryEntries,
  permanentDeleteGalleryEntries,
  createEntryId,
  makeProjectTag,
  makeNodeTag,
  makeWorkflowTag,
  makeBranchTag,
  makeSourceTag,
  getTagValue,
  hasTag,
  type GalleryEntry,
} from './galleryStore';
